### ISSUE TITLE
Не проходит построение контейнера

### ISSUE THREAD

**Issue by russinow** [TheDemonCat/onec-server#6]
валится на строке

`FROM ghcr.io/thedemoncat/onec_base:latest as base`

с такими вот сообщениями в логе

![image](https://user-images.githubusercontent.com/183291/113446603-5f998080-93f8-11eb-965e-64adf6f58e9c.png)

судя по написанному, не проходит авторизация на github registry. Но я не понимаю, какая там должна быть авторизация. Может быть не включен публичный доступ? Или есть какие-то другие варианты заставить это работать? ))

**Comment by thedemoncat** [comment]
Я тоже сперва понять не мог в чем дело, но оказалось, что доже для публичных контейнеров требуется авторизация в реестре github.

**Comment by russinow** [comment]
в принципе не так критично. Я победил, взяв инструкции из базового образа, вместо самого образа, и не понадобился доступ в github registry. За образы отдельное спасибо, они великолепны )))

но хочется все-таки понять что делать в такой ситуации. Я правильно понимаю, что если я туда залогинюсь, то есть если это будет не анонимный доступ, то все получится?

**Comment by thedemoncat** [comment]
Да. так и есть. В принципе, можешь заменить базовый контейнер на demoncat/onec-base:latest. Это тот же самый, только на hub.docker

**Comment by russinow** [comment]
спасибо. Все получилось. Закрываю с благодарностью )))

**Comment by thedemoncat** [comment]
Все таки я поменяю базовый образ на docker hub, что бы в дальнейшем не было проблем с авторизацией
Есть какие то вопросы по документации? Все ли понятно?

**Comment by russinow** [comment]
Поменять ссылку на докерхаб - отличная идея
С документацией все в порядке. Ее ровно столько, сколько нужно. Никаких проблем

Со всеми образами была ровно одна проблема, описанная в этом треде. В остальном - отличные образы для работы. Не только текущий, но и все остальные из набора
